/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginSimpleRouteImport } from './routes/login-simple'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DriverPanelRouteImport } from './routes/driver/panel'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as CustomerNotificationsRouteImport } from './routes/customer/notifications'
import { Route as CustomerEmergencyRouteImport } from './routes/customer/emergency'
import { Route as CustomerBookingsRouteImport } from './routes/customer/bookings'
import { Route as AdminVehiclesRouteImport } from './routes/admin/vehicles'
import { Route as AdminSosRouteImport } from './routes/admin/sos'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminPanelRouteImport } from './routes/admin/panel'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSimpleRoute = LoginSimpleRouteImport.update({
  id: '/login-simple',
  path: '/login-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPanelRoute = DriverPanelRouteImport.update({
  id: '/driver/panel',
  path: '/driver/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/customer/notifications',
  path: '/customer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerEmergencyRoute = CustomerEmergencyRouteImport.update({
  id: '/customer/emergency',
  path: '/customer/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/customer/bookings',
  path: '/customer/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSosRoute = AdminSosRouteImport.update({
  id: '/admin/sos',
  path: '/admin/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/panel',
  path: '/admin/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/driver/panel': typeof DriverPanelRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/login-simple': typeof LoginSimpleRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/emergency': typeof CustomerEmergencyRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/driver/panel': typeof DriverPanelRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/login-simple': typeof LoginSimpleRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/emergency': typeof CustomerEmergencyRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/driver/panel': typeof DriverPanelRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/login-simple': typeof LoginSimpleRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/emergency': typeof CustomerEmergencyRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/driver/panel'
    | '/help'
    | '/login'
    | '/login-simple'
    | '/signup'
    | '/test'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/panel'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/vehicles'
    | '/customer/bookings'
    | '/customer/emergency'
    | '/customer/notifications'
    | '/customer/profile'
    | '/admin/'
    | '/customer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/driver/panel'
    | '/help'
    | '/login'
    | '/login-simple'
    | '/signup'
    | '/test'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/panel'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/vehicles'
    | '/customer/bookings'
    | '/customer/emergency'
    | '/customer/notifications'
    | '/customer/profile'
    | '/admin'
    | '/customer'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/driver/panel'
    | '/help'
    | '/login'
    | '/login-simple'
    | '/signup'
    | '/test'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/panel'
    | '/admin/pricing'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/vehicles'
    | '/customer/bookings'
    | '/customer/emergency'
    | '/customer/notifications'
    | '/customer/profile'
    | '/admin/'
    | '/customer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  DriverPanelRoute: typeof DriverPanelRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  LoginSimpleRoute: typeof LoginSimpleRoute
  SignupRoute: typeof SignupRoute
  TestRoute: typeof TestRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPanelRoute: typeof AdminPanelRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSosRoute: typeof AdminSosRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  CustomerBookingsRoute: typeof CustomerBookingsRoute
  CustomerEmergencyRoute: typeof CustomerEmergencyRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-simple': {
      id: '/login-simple'
      path: '/login-simple'
      fullPath: '/login-simple'
      preLoaderRoute: typeof LoginSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/panel': {
      id: '/driver/panel'
      path: '/driver/panel'
      fullPath: '/driver/panel'
      preLoaderRoute: typeof DriverPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/emergency': {
      id: '/customer/emergency'
      path: '/customer/emergency'
      fullPath: '/customer/emergency'
      preLoaderRoute: typeof CustomerEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/customer/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sos': {
      id: '/admin/sos'
      path: '/admin/sos'
      fullPath: '/admin/sos'
      preLoaderRoute: typeof AdminSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/panel': {
      id: '/admin/panel'
      path: '/admin/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  DriverPanelRoute: DriverPanelRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  LoginSimpleRoute: LoginSimpleRoute,
  SignupRoute: SignupRoute,
  TestRoute: TestRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPanelRoute: AdminPanelRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSosRoute: AdminSosRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  CustomerBookingsRoute: CustomerBookingsRoute,
  CustomerEmergencyRoute: CustomerEmergencyRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
